### ISSUE TITLE
Support for basePath

### ISSUE THREAD

**Issue by fvarga** [ericdriggs/karate-test-utils#4]
Hi,

Thanks for this tool!

Is there a way how to configure API basePath or read it automatically from the Swagger doc for OpenAPI 2.0? 

As a quick workaround I edited the `schemeHostRegex` variable in `OpenApiPathRegexUtil`, but it's not very universal.

Thanks.

**Comment by ericdriggs** [comment]
Sounds like a good idea.
This is one of the areas where swagger 2.0 and open api 3.0 differ

swagger 2.0 only uses 1 basePath where open api supports multiple servers

Doing this right means covering both use cases

https://swagger.io/docs/specification/api-host-and-base-path/

**Comment by ericdriggs** [comment]
basePath added
https://github.com/ericdriggs/karate-test-utils/commit/f4f88e21913a36b39822918eb6d7d0fd18c08ff2

**Comment by ericdriggs** [comment]
split oas3 into separate issue

**Comment by fvarga** [comment]
Works great! Thank you
